name: fon_hakaton_2024
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^3.0.0
  rolling_bottom_bar: any
  google_fonts: ^6.2.1
  country_icons: ^3.0.0
  flutter_tts: 3.8.5
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/survivalmap2.png
    - assets/images/pengsquare.png
    # Add assets from the images directory to the application.
    
